# Generated by Django 4.2.6 on 2023-11-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_hosting', '0005_domain_domainpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainpurchase',
            name='domain',
        ),
        migrations.AddField(
            model_name='domainpurchase',
            name='domain_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
