# Generated by Django 4.2.6 on 2023-11-07 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar_hosting', '0006_remove_domainpurchase_domain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainpurchase',
            options={'verbose_name': 'Покупка домену', 'verbose_name_plural': 'Покупки доменів'},
        ),
        migrations.AlterModelOptions(
            name='hostingplan',
            options={'verbose_name': 'План хостингу', 'verbose_name_plural': 'Плани хостингу'},
        ),
        migrations.AlterModelOptions(
            name='hostingpurchase',
            options={'verbose_name': 'Покупка хостингу', 'verbose_name_plural': 'Покупки хостингу'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.AlterField(
            model_name='domainpurchase',
            name='domain_name',
            field=models.CharField(max_length=255, verbose_name="Ім'я домену"),
        ),
        migrations.AlterField(
            model_name='domainpurchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='domainpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='hostingplan',
            name='bandwidth',
            field=models.IntegerField(verbose_name='Трафік (МБ)'),
        ),
        migrations.AlterField(
            model_name='hostingplan',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='hostingplan',
            name='disk_space',
            field=models.IntegerField(verbose_name='Диск (МБ)'),
        ),
        migrations.AlterField(
            model_name='hostingplan',
            name='domains',
            field=models.IntegerField(verbose_name='Домени'),
        ),
        migrations.AlterField(
            model_name='hostingplan',
            name='free_domains',
            field=models.IntegerField(verbose_name='Додаткові домени'),
        ),
        migrations.AlterField(
            model_name='hostingplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='hostingplan',
            name='plan_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Ідентифікатор плану'),
        ),
        migrations.AlterField(
            model_name='hostingplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='hostingpurchase',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_hosting.hostingplan', verbose_name='План хостингу'),
        ),
        migrations.AlterField(
            model_name='hostingpurchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='hostingpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Логін'),
        ),
    ]
