# Generated by Django 4.2.6 on 2023-11-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_hosting', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
